### ISSUE TITLE
UI is not properly updating status in online registration

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#15274]
**Setup**
- Rancher version: 
Rancher Prime
[Rancher](https://github.com/rancher/rancher) v2.12.1
[Dashboard](https://github.com/rancher/dashboard) v2.12.1
[Rancher Prime CLI](https://github.com/rancher/cli) v2.12.1

**Describe the bug**
By registering a valid SCC registration code via online mode, the UI hangs with an indeterminate loading progress bar. By refreshing the page, the status of the registration is "Registered", indicating that it was successful. However, we should not need to refresh the page to have the status updated.

**To Reproduce**
1- Log in Rancher Prime with no active registration as admin
2- In Global settings, go to Registration
3- Select the online tab
4- Register a VALID registration code - (ping me @IsaSih if support is required on getting a valid SCC registration code)
5- Observe how the UI behaves after submition the registration code
6- Refresh the page if the UI hangs in the loading progress bar state

**Result**

https://github.com/user-attachments/assets/69b0a449-b581-4fd9-989d-495caf542b8e

**Expected Result**
The UI should display the change in the registration status without the need to refresh the page.

**Additional context**
It's inconsistent. Does not happen all the time.

**Comment by cnotv** [comment]
Once again: This is due architecture changes.

@gaktive this has been fixed with https://github.com/rancher/dashboard/pull/15247 while updating the architecture with https://github.com/rancher/dashboard/issues/15232
If we have to port it, we need just one.

**Comment by IsaSih** [comment]
Validated in 

[Rancher](https://github.com/rancher/rancher)	v2.13-98cb58105243b084ce0ce10eb82c785b7e19ad40-head
[Dashboard](https://github.com/rancher/dashboard)	master 433a02c
[Rancher Prime CLI](https://github.com/rancher/cli)	v2.12.0-rc.1

Reopening the issue, as I try to register a valid code, the DELETE request is sent to the backend, and the UI still hangs, not returning any error messages.

<img width="1716" height="889" alt="Image" src="https://github.com/user-attachments/assets/3c6eb947-dcce-421a-9180-992f2457a888" />

But checking the registrations, the request was successful

<img width="898" height="241" alt="Image" src="https://github.com/user-attachments/assets/35d70e42-8585-44b8-8f73-ca772947a32a" />

And the Registration Page doesn't reflect the successful registration

<img width="1463" height="256" alt="Image" src="https://github.com/user-attachments/assets/49e8ccff-c789-4a47-be12-eae001bb98a7" />

**Comment by cnotv** [comment]
> <img alt="Image" width="898" height="241" src="https://private-user-images.githubusercontent.com/70187881/485697848-35d70e42-8585-44b8-8f73-ca772947a32a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcwNjI4OTcsIm5iZiI6MTc1NzA2MjU5NywicGF0aCI6Ii83MDE4Nzg4MS80ODU2OTc4NDgtMzVkNzBlNDItODU4NS00NGI4LThmNzMtY2E3NzI5NDdhMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA1VDA4NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZmJhOTRjNzJmODI0YjVmZGU3MjdlYWQ5YzQ0ZTQwY2YxNWY1MDNjNmMwZTQyM2FmMzM5ZDMwMGZmN2M4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AVhy4i07-ampvDrq7wtfiE2_G8jxdnQUDxyPMiWG-jQ">
> And the Registration Page doesn't reflect the successful registration
> 
> <img alt="Image" width="1463" height="256" src="https://private-user-images.githubusercontent.com/70187881/485701897-49e8ccff-c789-4a47-be12-eae001bb98a7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcwNjI4OTcsIm5iZiI6MTc1NzA2MjU5NywicGF0aCI6Ii83MDE4Nzg4MS80ODU3MDE4OTctNDllOGNjZmYtYzc4OS00YTQ3LWJlMTItZWFlMDAxYmI5OGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA1VDA4NTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OWJhM2YyNmVhNDZiY2MyOWMxNjY5ZDdkZTlmMGJmZjVkNWIxY2UwMjg5OGIzZDA3YmVmZWY0M2RiNmZmNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mk_g40TknyZOam2WIw7dWpCzZQZQUPUyi535GKZGeak">

Sorry but State `Unavailable` means it's not registered correctly. Could you double check?

**Comment by IsaSih** [comment]
Works as expected. No longer needs to refresh the UI to see the registration code being succesfully registered.  Product name and expiration date correct. 
Validated in 

[Rancher](https://github.com/rancher/rancher)	v2.13-58abf492671b08c3fd9530a252c4ee8944335d9d-head
[Dashboard](https://github.com/rancher/dashboard)	master dbe9f30
[Rancher Prime CLI](https://github.com/rancher/cli)	v2.12.0-rc.1

<img width="1701" height="916" alt="Image" src="https://github.com/user-attachments/assets/a8552309-0b80-4983-831c-23839db31d83" />
