### ISSUE TITLE
Chart upgrade fails when upgrading from Installed Apps page

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/dashboard#15890]
**Setup**
- Rancher version: v2.13-481b9879b934a01413b1a93ae4f307a50cb6444a-head, v2.12-head, v2.12.3, v2.11.3
- Rancher UI Extensions: master `9ffcaff`
- Browser type & version:

**Describe the bug**
Chart upgrade fails when upgrading from the Installed Apps page.
   
Console error thrown when performing upgrade:
```
Error: Cannot find chartValues for  cattle-kubewarden-system/rancher-kubewarden-controller (chart secret has not been fetched via app `fetchValues`)
    at Proxy._validateSecret (catalog.cattle.io.app.js:437:13)
    at get chartValues (catalog.cattle.io.app.js:462:10)
    at Reflect.get (<anonymous>)
    at te.get (reactivity.esm-bundler.js:949:25)
    at Proxy.valuesYaml (catalog.cattle.io.app.vue:57:24)
```

**To Reproduce**

1. Go to local cluster -> Apps - Repositories -> add Kubewarden repository (Type: HTTP, URL: `https://charts.kubewarden.io`)
2. Go to Apps -> Charts -> search for Kubewarden, and install the chart (version 5.7.0)
3. Verify that kubewarden-controller version 5.7.0 and kubewarden-crds version 1.21.0 are installed
4. Go To Apps - Installed Apps
5. Click ellipsis (three dots menu)
6. Click Edit/Upgrade - Upgrade to 5.8.0
7. Observe: chart stuck in `Pending-Upgrade` state
8. Uninstall Kubewarden (may need to run to force uninstall `kubectl delete job rancher-kubewarden-controller -n cattle-kubewarden-system --ignore-not-found=true`)
9. Repeat steps 1-3
10. Go to Apps -> Charts -> search for Kubewarden, and click to upgrade the chart (upgrade to 5.8.0)
11. Observe: chart deploys successfully

**Result**
The upgrade fails with an error indicating that the chart secret has not been fetched. The chart gets stuck in `Pending-Upgrade` state.

**Expected Result**
When upgrading a chart from the Installed Apps page, the upgrade should proceed successfully without errors, similar to upgrading from the Repositories page.

**Screenshots**

**Upgrade fails when upgrading from Apps -> Installed Apps** ❌

https://github.com/user-attachments/assets/7025cd86-0f5b-4d5f-a68e-ea17f02aab54

<img width="1371" height="883" alt="Image" src="https://github.com/user-attachments/assets/3e5a0f22-80e7-4bca-9d7d-6b0499c67974" />

---

**Upgrade passes when upgrading from Apps -> Charts -> Chart** ✅

https://github.com/user-attachments/assets/7e6a689e-dd51-46b7-8fa9-476dd46c5a66

**Additional context**
Discovered while testing https://github.com/rancher/dashboard/issues/15710
Workaround: Upgrade from Apps -> Charts -> Chart page

**Comment by momesgin** [comment]
I was able to reproduce this in 2.11 too. It took me a while to finally figure out where the problem is. If you don't provide the container registry value `ghcr.io` the upgrade fails:

<img width="1976" height="1728" alt="Image" src="https://github.com/user-attachments/assets/6daaf424-3d4d-4b67-8ef9-595a3ea8a178" />

When you select a new version from the dropdown we reset the value for the container resgistry field. I'm not 100% sure if we should always re-apply this value. I need to investigate this further.

**Comment by momesgin** [comment]
I think as part of fixing this we should display Upgrade/Edit current version/Downgrade options rather than only Edit/Update. This will be consistent with the rest of the places where we have these actions, e.g. on Cluster Tools page:

<img width="963" height="545" alt="Image" src="https://github.com/user-attachments/assets/5f09ec2a-2cd1-4574-a1ec-0cec72194e51" />

cc @oboc-sts

**Comment by oboc-sts** [comment]
> I think as part of fixing this we should display Upgrade/Edit current version/Downgrade options rather than only Edit/Update. This will be consistent with the rest of the places where we have these actions, e.g. on Cluster Tools page:

Yes, please 😃  Very much so, if possible. Whenever we touch some of these "charts related" areas, we should strive to improve them by aligning them with the previously agreed rules we've already implemented. Consistency ftw 💪 

Thanks for bringing this fwd @momesgin

**Comment by momesgin** [comment]
I created a [separate issue](https://github.com/rancher/dashboard/issues/16181) for splitting the chart update actions into Upgrade/Edit/Downgrade.

**Comment by yonasberhe23** [comment]
E2E coverage is good for the main scenario but manual QA is still needed to verify edge cases, the original issue scenario (upgrading from Installed Apps page), and ensure no regressions in other form fields or the installation process.

**Comment by IsaSih** [comment]
My findings while testing this issue:
I still see the 'Chart secret not fetched' error in the console, but the terminal and the UI show a successful upgrade.
```
 Cannot find chartValues for  cattle-kubewarden-system/rancher-kubewarden-controller (chart secret has not been fetched via app `fetchValues`)
    at Proxy._validateSecret (
```

https://github.com/user-attachments/assets/922406f7-9d28-470f-bac1-e5389955eb33

Is this expected or should we not see this error in the console at all? @momesgin I had the checkbox 'Container Registry for Rancher System' selected and the registry set as ghcr.io. 
The exact same behavior occurs when the checkbox is not selected.

When installing from the Apps marketplace, the installation is successful, and this error is not displayed in the console at any stage.

https://github.com/user-attachments/assets/2bdd62bf-f03d-4ca4-bed5-2ebda97c4bc8

**Comment by momesgin** [comment]
@IsaSih I missed checking that error on the console, my focus was to make sure the upgrade finishes successfully. I'm able to see the console error whenever I'm redirected to that detail release page during the upgrade `/c/local/apps/catalog.cattle.io.app/cattle-kubewarden-system/rancher-kubewarden-controller#resources`. Will raise a PR soon.

**Comment by IsaSih** [comment]
Validated in 

Component	Version
[Rancher](https://github.com/rancher/rancher)	v2.14-171eefb6a7573ba00ba586406a4a416716060558-head
[Dashboard](https://github.com/rancher/dashboard)	master b8c97d3
[Rancher CLI](https://github.com/rancher/cli)	v2.12.0-rc.1

Fixes all addressed

<img width="1697" height="913" alt="Image" src="https://github.com/user-attachments/assets/ba3b9e8a-b7de-45db-912c-19dd9a1ead6b" />

.
