### ISSUE TITLE
Unable to edit the clusters created from rke1 templates from cluster management page as a cluster owner post rancher upgrade

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5395]
Setup

Rancher version: 2.6-head 80465bd
Browser type & version: Chrome

**Describe the bug**
I have 2 clusters - 1 created from an rke template - template1 and the other without an rke template - cluster1. Added a standard user as a cluster owner in both the cluster. After upgrading the rancher server to 2.6-head from 2.5.12, when I try to edit the cluster c1 as the cluster owner from cluster management page, I see the edit config page loaded with all the details. 
If I try to edit the template1, I see no details loaded in the edit config page and now if we try to edit the cluster1, we do not see the details loaded for cluster1 as well

**To Reproduce**
As an admin
1. On 2.5.12, create an rke1 node driver with 1 etcd, 1 cp, 1 worker - c1 on k8s 1.20
2. create an rke1 template 
3. In the advanced options of the rke1 template, enable etcd snapshot with s3 enabled and also enable the `allow user override` option.
4. Create a cluster with this template with 1 worker, 1 etcd and 1 cp - t1 on k8s 1.20
5. Create a standard user user1 from users & auth and add the user to both the clusters as a cluster owner.
6. Upgrade rancher server to v2.6-head 
7. Log in as user1 and edit the cluster c1 - all details are loaded.
8. Edit the cluster t1

**Result**
No details are loaded other than Member roles/Labels & annotations
Now edit the cluster c1 and see that similar to t1 no details are loaded other than roles/labels&annotations.

**Expected Result**
Expected all the details to load as cluster owner can edit the cluster config.

**Screenshots**

https://user-images.githubusercontent.com/38144301/158309804-31557b71-7345-4c24-ae50-7e0b1c45a593.mp4

**Additional context**
I do not see any console errors other than
```
 Subscribe ignoring message, current=c-tst8g socket=c-jq5cv (sockId=5)
```

I'm able to edit the cluster t1 as a cluster owner via postman.

**Comment by cnotv** [comment]
@anupama2501 do you have a dump of the response, so we can verify if there's not some issues from the data retrieved? It does not seems related to the client on a first glance.

**Comment by gaktive** [comment]
@anupama2501 do you have this cluster up somewhere for @catherineluse to access and view the browser logs?

**Comment by anupama2501** [comment]
Provided the setup to @catherineluse via slack

**Comment by catherineluse** [comment]
After looking into it on Anupama's setup I think it's a permissions issue where the cluster owner can't get node template details from the backend.

The problem stems from the fact that for a cluster owner, the dashboard is not passing the right prop into the iFramed Ember page.

When the admin is logged in, the ember page gets this `src` prop, which tells ember we need the cluster edit form for Digital Ocean:

```
src:"/c/c-v9nsf/edit?provider=digitalocean"

```
But when user1 is logged in, the ember page gets this `src` prop:

```
src:"/c/c-v9nsf/edit?provider"
```
In that case, `digitalocean` is not passed in, so without the driver, ember doesn't know what to render.

The UI gets the `provider` name by looking at a machine pool and then looking up the node template that it uses. It can see the name of then node template on the machine pool. Then it tries to look up the node template by ID and get details from there including the name `digitalocean`. But it looks like the cluster owner does not have permission on the back end to get a node template by ID. For the cluster owner, getting the node template by ID always returns undefined: https://github.com/rancher/dashboard/blob/master/models/management.cattle.io.nodepool.js#L8

If we look at the API view for getting the node template by ID, it says the cluster owner doesn't have permission:

<img width="837" alt="Screen Shot 2022-03-17 at 1 55 07 AM" src="https://user-images.githubusercontent.com/20599230/158774745-3f2fe2b7-c472-4d4c-b34e-75e3b7a7dc53.png">

I think the cluster owner should have access to node templates because they already have access to machine pools. So to me it looks like a backend issue.

**Comment by catherineluse** [comment]
After talking to Anupama it sounds like it's more complicated. It seems that form fields are only hidden if you have override values.

I checked the ember UI and when you edit the RKE1 cluster in ember, we pass another parameter in the URL called `clusterTemplateRevision`:

```
https://44.234.71.171/c/c-jmhqj/edit?clusterTemplateRevision=cattle-global-data%3Actr-7ql4m&provider=digitalocean
```
I'm currently looking into whether the dashboard needs to provide that parameter as well.

**Comment by catherineluse** [comment]
### Root cause

- The reason that most fields weren't rendering was because the RKE template version was not being passed into the iFramed Ember page, but it was a required value.
- The reason that navigating to one Edit Config form would break another one is that the parameters for the iFramed ember page were only computed once, so the same parameters were incorrectly being used for multiple forms.
 
### What was fixed, or what changes have occurred

- The cluster edit page now checks the cluster data to see if it was made from an RKE template. If it was, it passes the RKE template version into an iFramed ember page.
- I changed the ember parameters so that they are now refreshed for each cluster config form.
 
### Areas or cases that should be tested
- cluster config form for a cluster that was created from an RKE template with overrides
- cluster config form for a cluster that was created from an RKE template that does have overrides, and the overrides are being used
- cluster config form for an RKE cluster that was not created from an RKE template
 
### What areas could experience regressions?
Same as the areas that should be tested
 
### Are the repro steps accurate/minimal?
I think it's probably not necessary to upgrade rancher first. I think you can reproduce the issue just by provisioning RKE1 clusters from RKE templates.

**Comment by sowmyav27** [comment]
**On 2.6-head commit id 024e6fa**

- Deploy an RKE1 template
- As an admin using this template, deploy an RKE1 cluster
- add user1 as cluster owner
- login as this user
- Edit cluster
- User is able to edit cluster as on 2.5.12, and view the config of cluster
- As a std user/cluster owner, user is not able to edit config of an RKE2/k3s cluster which user was added as cluster owner. Logged this issue - https://github.com/rancher/dashboard/issues/5442. Not sure if this is a related bug.

**Comment by sowmyav27** [comment]
Reopening for few more checks.

**Comment by anupama2501** [comment]
Re-opening as I see the issue persist for rke1 templates with overridden values. Upgraded the rancher server from 2.6.3 >> 2.6-head 9146220

1. On 2.6.3, created an rke1 template with overridden values - k8s 1.21, s3 etcd snapshots enabled and allow user override option enabled.
2. Created a cluster with this template - cluster1
3. Added a standard user as a cluster owner in this cluster.
4. The cluster configs are not loaded for cluster owners when we try to edit the cluster config.
5. I also noticed that the clusters without any templates cluster-no-templates are editable but if we edit cluster1 with overridden templates and go back to edit the clusters without any templates, the clusters configs `cluster-no-templates` becomes non editable too.

In the ticket https://github.com/rancher/dashboard/issues/5442, the rke2/k3s clusters were created in the rancher server that has clusters created with rke1 templates. This is similar to the point5 mentioned above.

**Comment by catherineluse** [comment]
On v2.6-head, it looks like the cluster owner's changes are being saved in the cluster YAML. But the new values are not showing up in the form.

**Comment by catherineluse** [comment]
I'm seeing this issue on v2.6.3, not just v2.6-head. Except on v2.6.3, the new values are saved in YAML for the admin but not the cluster owner.

This issue is very similar to https://github.com/rancher/dashboard/issues/5032 - The RKE template's default values are always being shown, even after values are edited.

**Comment by catherineluse** [comment]
Nancy proved that the problem is on the Ember side. When you edit the values in Ember, it looks like they are saved at first. But when you refresh the page, the form reverts to the incorrect values.

Meanwhile the values in the API view are correct.

**Comment by catherineluse** [comment]
## QA Template

### Root cause

For clusters created from RKE templates, the Ember UI was not populating the "questions" or overridable values with existing cluster config values.
 
### What was fixed, or what changes have occurred

Created a PR to Ember https://github.com/rancher/ui/pull/4822 which uses the existing cluster config values as defaults in the edit cluster form.
 
### Areas or cases that should be tested
- cluster config form for a cluster that was created from an RKE template with overrides
- cluster config form for a cluster that was created from an RKE template that does have overrides, and the overrides are being used
- cluster config form for an RKE cluster that was not created from an RKE template
 
### What areas could experience regressions?
Same as the areas that should be tested
 
### Are the repro steps accurate/minimal?
I think it's probably not necessary to upgrade rancher first. I think you can reproduce the issue just by provisioning RKE1 clusters from RKE templates.

**Comment by anupama2501** [comment]
Verified on v2.6-head 6f9c19d

1. As an admin created 4 node drivers RKE1 clusters 1 with rke template no values overridden, 1 with rke template values overridden, 1 with rke template revised and 1 with no cluster templates.
2. Added a user as cluster owner to all 4 clusters
3. Edited configs as a cluster owner and verified all the details are loaded and updated values are applied on the cluster.
4. Verified as an admin, editing the config loads and able to edit the config of the clusters.
