### ISSUE TITLE
Cronjob backoffLimit not upgrading in UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5422]
Internal reference: SURE-3048
Reported in 2.5.8

Issue description:
The field is `spec.jobTemplate.spec.backoffLimit` is not being added to the deployment when updated via the UI.

Business impact:
User manually added the field.

Repro steps:

- Deploy example cronjob
- Upgrade the cronjob via the UI
- Change backoffLimit to "0"

Actual behavior:
`spec.jobTemplate.spec.backoffLimit` will be missing from the YAML

Expected behavior:
`spec.jobTemplate.spec.backoffLimit` should be set to zero.

**Comment by nwmac** [comment]
Looks like we are treating 0 as a falsey and not adding the value in.

**Comment by neillsom** [comment]
This seems to be indicative of a greater problem relating to updating fields through `UnitInput` component. It appears that the root of the issue is a recent PR ([5670](https://github.com/rancher/dashboard/pull/5670)) which adds a default debounce delay value of 500ms on field input. Any value other than 0 prevents the form from saving through edit config.

**Comment by nwmac** [comment]
@cnotv I think your fix will address this?

**Comment by cnotv** [comment]
@neillsom PR here if you want https://github.com/rancher/dashboard/pull/5965

**Comment by nwmac** [comment]
Should be fixed when https://github.com/rancher/dashboard/pull/5965 merges

**Comment by cnotv** [comment]
It may be worthy to create unit test for this issue anyway, as we cannot guess to break some other logic somewhere else.

**Comment by cnotv** [comment]
It may be worthy to also explain what is supposed to be the logic while parsing the % value, as we lack of unit tests for that case as well.

**Comment by cnotv** [comment]
#5965 has been merged and we can proceed with this issue.

**Comment by neillsom** [comment]
@cnotv I'm still seeing unexpected behavior in the UnitInput components. Do you have any ideas what is causing this? https://www.screencast.com/t/44Xacnnaex

**Comment by cnotv** [comment]
Uhm this is weird as it seems not related with my changes then. I'll try to navigate back in the history to figure it out what caused it. The issue seems on more pages and also related to other components.
The % reset is caused by the component `InputWithSelect`.

**Comment by cnotv** [comment]
The percentage issue seems to be present since 2.6.4.

**Comment by cnotv** [comment]
The issue seems not related with the components at all.
As you can see in the video this is also not limited to the Cronjob only as well, rather with the scaling tab, as it happens also for the Deployment.
Other tabs, e.g. Resources, do not seem to be affected.


https://user-images.githubusercontent.com/5009481/170664201-b5f50ba5-00d7-4c0e-b02d-dd6a396d4b0b.mov

**Comment by cnotv** [comment]
@nwmac @neillsom 
Ok the issue seems indeed related to the latest changes to `UnitInput` component and the reason this does not happen everywhere is quite simple: 
The `value` prop is updated [at every input in the whole container] (https://github.com/rancher/dashboard/blob/master/shell/edit/workload/Upgrading.vue#L193), on top of some exceptions:
```html
  <div @input="update">
```
Since now we use blur for the input, this workaround stopped to work as planned, so in order to actually track the changes, it's required to:
- Type the first time the value
- Blur out from the current input
- Type again somewhere else

Not so sure which convoluted code we should tackle down: the UX parsing of the UnitInput or identify every container input logic.

**Comment by neillsom** [comment]
@cnotv PR [6070](https://github.com/rancher/dashboard/pull/6070) appears to have fixed this issue. 

Steps used for testing
1. Checkout pr 6070 locally
2. Create new cronjob with minimum default values (name, schedule, image)
3. Edit Config > Scaling and Upgrade Policy > set Backoff Limit to 0 > Save

Input values are saved correctly.

Moving to test.

**Comment by nwmac** [comment]
@neillsom The PR that fixes this is still in draft/review, so this shouldn't move to test until the fix has been merged.

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 772b2f0
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. Deploy example cronjob - set backoffLimit to 1
2. Upgrade the cronjob via the UI
3. Change backoffLimit to "0"
4. Deploy another cronjob without setting backoffLimit value
5. Upgrade the cronjob via the UI
6. Set backoffLimit to "0"

**Result** - Pass

The backoffLimit value is set successfully and is not missing from the YAML after upgrading the cronjob via the UI
![image.png](https://zube.io/files/rancher/e786206b45b71bd3b9e70eec03db48b6-image.png)
