### ISSUE TITLE
RKE2 Node's external IP is set as the internal IP

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5603]
**Rancher Server Setup**
- Rancher version: 2.6head commit id: `11a7451`
- Installation option (Docker install/Helm Chart): docker install

**Information about the Cluster**
- Kubernetes version: `v1.21.9+rke2r1`
- Cluster Type (Local/Downstream): Linode node driver cluster - 1 etcd, 1 cp and 3 worker nodes. Container network - `Cilium`

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Standard user
   
**Describe the bug**
Node's external IP is set as the internal IP

**To Reproduce**

- Deploy an RKE2 cluster Linode
- Wait for the cluster to come up Active.
- Navigate to Cluster Explorer --> Nodes --> External and Internal IP
- The nodes have 1 IP address and the Internal IP addresses are set. The external IP addresses = `None`
- Yaml of the node also has the internal IP set
```
status:
  addresses:
  - address: Ip
    type: InternalIP
  - address: sowmya-cilium-pool1-83e7c181-xwv4t
    type: Hostname
```

**Expected result:**
The Ip is the external IP.

**Comment by thedadams** [comment]
The difference here is that in the RKE1 land, the user has the ability to specify that they want the node to have a private IP address. If they select the checkbox when creating the node template for an RKE1 cluster, then the private IP address is added.

In RKE2 provisioning, the user doesn't have this opportunity. If the checkbox existed for Linode provisioned clusters, then the backend should be setup to handle this (it does correctly for EC2 nodes, for example).

@gaktive This was in our v2.6.5 milestone which is why I put that milestone here.

**Comment by richard-cox** [comment]
Is this a Linode only issue or can it be tested in Digital Ocean? Are there group linode credentials that can be used to implement this (our individual access was removed... because we didn't need them?)

What properties should be set on which resource?

**Comment by richard-cox** [comment]
@thedadams sorry to question, haven't investigated fully yet so this might be super obvious, but is it a property in `provisioning.cattle.io.cluster` that needs to be set?

**Comment by thedadams** [comment]
@richard-cox No problem. It's a property on the `DigitalOceanConfig` or `LinodeConfig` objects that needs to be set: `privateNetworking` in the former and `createPrivateIp` in the latter.

**Comment by richard-cox** [comment]
Ok, for DO we do allow setting a `privateNetworking` value, it's just sneakily hidden under additional options `Private Networking`

![image](https://user-images.githubusercontent.com/18697775/165127804-05f48e8e-b7ca-49e5-939f-83bd1448d9cf.png)

For Linode though there's nothing. I've implemented a fix... but have no way of validating it. 

![image](https://user-images.githubusercontent.com/18697775/165130345-e93e726f-8a72-4be3-b532-830178680407.png)

The change submits the below json to `v1/rke-machine-config.cattle.io.linodeconfigs/fleet-default`. Most of it is junk (no creds to get proper info...) but shows the `createPrivateIp` at the root level.

@thedadams if this looks correct i'll submit a PR. If you fancy validating it first i can create a build that can be tested by changing the `ui-dashboard-index` setting, just let me know

```{
   "createPrivateIp":true,
   "image":"linode/ubuntu20.04",
   "instanceType":"g6-standard-2",
   "metadata":{
      "annotations":null,
      "finalizers":[
         
      ],
      "generateName":"nc-undefined-pool1-",
      "labels":null,
      "managedFields":[
         
      ],
      "namespace":"fleet-default",
      "ownerReferences":[
         
      ]
   },
   "region":"us-west",
   "type":"rke-machine-config.cattle.io.linodeconfig",
   "interfaces":[
      
   ]
}```

**Comment by thedadams** [comment]
I tested this with Linode and enabling the private IP address checkbox that @richard-cox added and the node was assigned a private IP as expected.

**Comment by sowmyav27** [comment]
**On 2.6-head commit `7db4fe4`**

- Deployed an RKE2 Do and Linode RKE2 cluster
- Private Networking is enabled on both the clusters
- DO nodes show only Internal IP. External IP still shows None
- Linode - Both IPs are seen on the Nodes page. But [this](https://github.com/rancher/rancher/issues/37500) issue is seen.

@richard-cox Are we not fixing this for DO ?

**Comment by richard-cox** [comment]
@sowmyav27 From the UI's perspective I think we're providing the correct values for both DO and Linode
- For DO, when `Additional DigitalOcean Options --> Private Networking` is checked, we POST the following to `v1/rke-machine-config.cattle.io.digitaloceanconfigs/fleet-default`  (note the `privateNetworking` `true').
  ```
  {
     "image":"ubuntu-20-04-x64",
     "metadata":{
        "annotations":null,
        "finalizers":[
           
        ],
        "generateName":"nc-rc-rke2-2-pool1-",
        "labels":null,
        "managedFields":[
           
        ],
        "namespace":"fleet-default",
        "ownerReferences":[
           
        ]
     },
     "privateNetworking":true,
     "region":"lon1",
     "size":"s-4vcpu-8gb",
     "type":"rke-machine-config.cattle.io.digitaloceanconfig"
  }
  ```
- For Linode we do as per https://github.com/rancher/dashboard/issues/5603#issuecomment-1108777558

@thedadams From our conversations above I think the UI is doing the right thing, if so would you like a new issue or for us to transfer this over? If not could you confirm `privateNetworking` on DO is still correct?

**Comment by sowmyav27** [comment]
Closing this issue as Linode works and DO -- is a backend issue.

**Comment by richard-cox** [comment]
Marking as blocked, once https://github.com/rancher/rancher/issues/37510 is resolved this will also be resolved.

**Comment by CyberPoison** [comment]
Same issue here with Hcloud a.k.a Hetzner Cloud when checked the box it inverts the internal to external and vice versa.

**Comment by gaktive** [comment]
37510 now resolved for 2.6.7 so UI can proceed.

**Comment by Josh-Diamond** [comment]
Ticket #5603 - Test Results [pt. 2]

With HA Helm:

Verified on rancher `v2.6-988b8d1f63c19b13f6afba9de2e34e30cac133a7-head`:
1. Fresh install of rancher `v2.6-head`
2. Provision a downstream RKE2 Linode Node driver cluster
3. Once cluster is provisioned and Active, navigate to `Cluster Explorer` => `Nodes` => `IP Address`
4. Verified - `External/Internal IP` field has been changed to `IP Address` and reflects external address, as expected

Screenshots:

`Step 4 - Cluster Details => Machine Pools`
![screenshot1](https://user-images.githubusercontent.com/46494969/179296669-48472e77-84f6-491e-9385-d9e6db4495d2.png)

`Step 4 - YAML of cp node`
![screenshot2](https://user-images.githubusercontent.com/46494969/179296843-c4779aa9-3982-45c5-8059-96b95bb4b48b.png)

**Comment by devopswhw** [comment]
This seems broken again to me. Latest versions of everything, custom cluster on hetzner. Not sure how you are trying to guess the IP addresses here.

**Comment by artiommocrenco** [comment]
This looks broken again to me.

Not sure why one would try to guess an IP address instead of letting users specify it as k3s does.
