### ISSUE TITLE
Change way supported version is detected

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6665]
Currently we use the subscription ID setting.

Change this to use the metadata from the new `/rancherversion` endpoint - see: https://github.com/rancher/rancher/pull/38445/files

We should add a request to this API when the UI loads - before login and store that data. This will not change.

We can do this now and if we get a 404, we should populate empty data and store that the UI is not a supported deployment.

**Comment by slickwarren** [comment]
I’m not sure what all should be tested besides testing that /rancherversion has a response. Could I get the QA template filled out for this one?
I currently get the following response: {"Version" : "<rancher_version>", "GitCommit" : "<gitcommit>", "RancherPrime" : "false"} is that all that is expected? Also, when using 2.7-head, the `Version` value is the same as GitCommit. 

here is my current test plan:
* test /rancherversion response on community version (see question above)
* test /rancherversion response on non-community version (tbt)
* possibly test upgrade from 2.6 (should have no response for rancherversion) -> 2.7

**Comment by nwmac** [comment]
@slickwarren This was to make sure we wired up non-community detection to the new version endpoint.

To validate:

- As community, check that the browser makes a request to /rancherversion and the response indicates community. Verify on the UI that the home page shows the 'Commercial Support' link on the right hand panel

- As non-community, check that the browser makes a request to /rancherversion and the response indicates non-community. Verify on the UI that the home page does not show the 'Commercial Support' link on the right hand panel

**Comment by Shavindra** [comment]
Further instructions: https://github.com/rancher/dashboard/pull/6736#issue-1349291691

@slickwarren 

Could also be resolved by:
PR
https://github.com/rancher/dashboard/pull/7131

Issues:
https://github.com/rancher/dashboard/issues/6663
https://github.com/rancher/dashboard/issues/6665

**Comment by slickwarren** [comment]
Similar / related issue that may have been part of these changes: There is no longer an option on the support page to enter a subscription ID. Perhaps related to the way version is detected? Or in other words, perhaps another reason that commercial support option still appears (because subscription ID is not set)
![Screen Shot 2022-10-28 at 11 10 03 AM](https://user-images.githubusercontent.com/16691014/198704371-517f2d83-e5d8-48aa-b4cb-cf6d9bb68343.png)

**Comment by nwmac** [comment]
@slickwarren 

"on a non-community version of rancher (docker installed), the response does not indicate it is non-community version. I believe that due to this, the commercial support option still shows up in the UI, though all of the branding is correctly showing the non-community brand."

That sounds like a backend issue - we rely on the `/rancherversion` endpoint telling us if it a the community version or not.

Regarding the subscription ID change, that is intentional - this is no longer needed to determine if it is a supported install - that is done from the `/rancherversion` endpoint metadata

**Comment by jiaqiluo** [comment]
can be validated in non-community version v2.7.0-rc8

**Comment by slickwarren** [comment]
tested on v2.7.0-rc8: 
* check /rancherversion on non-community version (now set to true) -- pass
* check /rancherversion on community version (should set to false) -- pass
