### ISSUE TITLE
Imported AKS clusters incorrectly show a K8s upgrade message in the nodepool section, regardless if you have updated the cluster's K8s version

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#8501]
**Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/2b2ed443065a9f38c4c5764461be33823eb6fec3
- Browser type & version: Chrome

**Describe the bug**

Upon importing a private AKS cluster into Rancher, I wished to upgrade from v1.24.9 to v1.25.5. The upgrade itself was successful, but I noted that when I edited the cluster configuration, I saw this message in the nodepool before I even changed the K8s version:

![image](https://user-images.githubusercontent.com/52591819/227038704-916a300f-4469-4e22-a046-e36350c4040c.png)

The above message makes sense when I am editing my cluster and I then proceed to update the K8s version. However, I did not update the K8s version at all, but still see this message. As such, if a user has not selected a new K8s version, we shouldn't be showing any message. If a user does select an upgraded K8s version, then we should show this message.

Additionally, I tested provisioning a hosted AKS cluster from Rancher and doing the same workflow, I DO NOT see this issue. After I updated the K8s version, only then did this warning message appear. That is the behavior I would expect, regardless of the AKS cluster being imported or provisioned directly from Rancher.

**To Reproduce**

1. As a standard user, navigate to Cluster Management > Import Existing > Azure AKS.
2. Fill out the requested information and import an existing AKS cluster into Rancher
3. Validate that the cluster and nodes come up as `Active`.
4. Edit the cluster's configuration and scroll down to the node pool section without updating the K8s version for the cluster; you will see this message.

**Result**
Imported AKS clusters that have not updated the K8s versions yet show aforementioned message in the nodepool section.

**Expected Result**

Imported AKS clusters should only show the aforementioned message in the nodepool section when a user has updated the cluster's K8s version.

**Comment by gaktive** [comment]
We can check the behaviour once we complete the migration of AKS provisioning from Ember to Vue.

**Comment by yonasberhe23** [comment]
seems like there are no e2e/unit tests attached to the fix (I'm guessing it's because we don't have a way to create clusters in a cloud provider - please advise @mantis-toboggan-md) so we'll need to manually test this. moving to To Test

**Comment by markusewalker** [comment]
Still seeing this issue on `v2.8-head` https://github.com/rancher/rancher/commit/70e0ba14c87430734dc1543aa3a0be1b988a04c7.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/70e0ba14c87430734dc1543aa3a0be1b988a04c7

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Imported AKS cluster's nodepool section does not show upgraded message on non-upgraded cluster|:x:|

**REPRODUCTION STEPS**
1. Setup Rancher v2.8-head.
2. Imported an AKS cluster that I created previously in Azure Dashboard (v1.27.1).
3. Edited the cluster config without updating the K8s version and still see the message:
![image](https://github.com/rancher/dashboard/assets/52591819/66844d25-b23f-4996-86f8-f8e885cec95d)

![image](https://github.com/rancher/dashboard/assets/52591819/24117cab-9267-4a2c-9ea9-32980782f309)

**Comment by mantis-toboggan-md** [comment]
@markusewalker this should be fixed in 2.9-head, not 2.8-head

**Comment by mantis-toboggan-md** [comment]
@yonasberhe23 there are unit tests tied to this functionality - the bug is not tied to imported clusters specifically 
https://github.com/rancher/dashboard/blob/master/pkg/aks/components/__tests__/AksNodePool.test.ts#L54-L179

**Comment by markusewalker** [comment]
@mantis-toboggan-md thanks for the clarification! I will proceed to test on v2.9-head and validate/close if all is good.

**Comment by markusewalker** [comment]
Still seeing this issue on `v2.9-head` https://github.com/rancher/rancher/commit/ed485b2dfdd6dd69a93d6c7b8ff7b672bc9696c0.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.9-head` https://github.com/rancher/rancher/commit/ed485b2dfdd6dd69a93d6c7b8ff7b672bc9696c0

**TEST RESULTS**
|#|Scenario|Result|
|---|---|---|
|1|Imported AKS cluster's nodepool section does not show upgraded message on non-upgraded cluster|:white_check_mark:|

**REPRODUCTION STEPS**
1. Setup Rancher v2.9-head.
2. Imported an AKS cluster that I created previously in Azure Dashboard (v1.28.10).
3. Edited the cluster config without updating the K8s version and validated that the message is not there.
