### ISSUE TITLE
[SURE-6536] Cluster labels cannot be removed, updated or modified

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9563]
Internal reference: SURE-6536
Reported in 2.7.3 & 2.7.4

Issue description:
Cluster labels are deleted or overwritten when modified or added.

Business impact:
Fleet operates by targeting cluster groups however clusters cannot be consistently added or removed from groups because the label changes get overwritten by Rancher.

Troubleshooting steps:
- View cluster labels
- Edit the cluster labels
- Save changes
- Wait a moment (sometimes the change takes effect only to be overwritten shortly thereafter) - in fleet this causes workload flapping.
- View cluster labels - note the change did not stick

Repro steps:
- Create a downstream cluster - import k3s e.g.
- Add a label during cluster creation or afterward.
- Try to remove or modify the label

Workaround:
None

Actual behavior:
Cluster labels are reverted to the state before the change is made.

Expected behavior:
Cluster label changes according to the edit 

Additional notes:
An internal person was able to reproduce this with a k3s cluster created via the node driver and also with imported clusters, though they have not tried other cluster types.

A fix was done for 2.7.5 via https://github.com/rancher/ui/pull/4975 but from that person's tests:

> My tests included an imported k3s cluster and an aws node driver cluster. I did not test with Elemental clusters.

Imported k3s cluster
- Labels can be added to a cluster at the time of cluster creation [SUCCESS]
- Labels can be added to a cluster after cluster is provisioned [SUCCESS]
- Labels can be deleted from a cluster if they were added after the cluster was provisioned [SUCCESS]
*- Labels cannot be deleted from a cluster if the label was added during cluster creation [FAIL]*
- Labels can be edited in a cluster if the the label was added after the cluster was provisioned [SUCCESS]
*- Labels cannot be edited if the label was added during cluster creation [FAIL]*

Hostbusters (@snasovich) offered some guidance from the backend standpoint and it was determined that the user tried this example:

> I create a couple labels during the process of cluster creation "Import -> Labels and Annotations -> Add Label"
```
geo: "ny"
managed: "yes"
```
> If I try to delete these labels, doing "Edit Config" on the cluster from the "Manage Clusters" page, it appears to delete from the UI but after saving the form, the Label is still there.

> Also, if I "Edit Config" and try to modify the value of the label. 
```
managed: "no"
```
> for example, then it appears to change the value on the form but in fact the value is not changed when I save the form. Go back in to view it - go back to config view or edit yaml to see it is unchanged.

> By the way, that is all via the "Manage Clusters" page.

> I just tested the same operations via "Continuous Delivery" and on the surface it appears to work but if you go back in to edit configs, you can see that it did not work. It does not help that these pages show different (inaccurate) information.

**Comment by richard-cox** [comment]
ok, i'm late to the party. This will be resolved via https://github.com/rancher/dashboard/issues/9476

**Comment by richard-cox** [comment]
To clarify
- Syncing between `v3/clusters` and `v1/provisioning.cattle.io.clusters` resources is a tenet of those resource types. This has always been the way since the creation of v1 / steve. The failure to sync labels between these resources is a backend bug.
- The work to support editing of imported clusters in https://github.com/rancher/dashboard/issues/9476, assigned to Eva, will make that bug superfluous, as no syncing will be required.

**Comment by richard-cox** [comment]
@eva-vashkevich I've assign this back to you. Can you keep it in sync (zube column and milestone) with https://github.com/rancher/dashboard/issues/9476?

**Comment by eva-vashkevich** [comment]
Created BE issue https://github.com/rancher/rancher/issues/43191
Steve API does not provide us information required to edit imported cluster.

**Comment by gaktive** [comment]
Backend should have unblocked this for UI and now we're blocking them. Moving to Next Up.

**Comment by gaktive** [comment]
For those folks who run into this, there is a workaround: update the labels on `clusters.provisioning.cattle.io` objects via `kubectl`.

**Comment by mmartin24** [comment]
FTR: our UI e2e tests for fleet have noticed an increase on the failiures due to this since 2.9 ([example](https://github.com/rancher/fleet-e2e/actions/runs/11267274970/job/31333112816#step:9:410)) while removing labels. while it seemed to have been relatively ok in 2.8.
![image](https://github.com/user-attachments/assets/a96a29ed-a293-4872-8fe7-ae53b60c6cb2)

**Comment by torchiaf** [comment]
Related issue: https://github.com/rancher/dashboard/issues/11241

**Comment by kinarashah** [comment]
@eva-vashkevich FYI, backend PR for this issue has been merged.

**Comment by mantis-toboggan-md** [comment]
Fixed by https://github.com/rancher/dashboard/pull/13332

**Comment by izaac** [comment]
Rancher version: `v2.11-41098eee7331faf5d4a478dfcf66232867ed6a6f-head`
UI Version: `master 95c0062`
Firefox version: `135.0.1`

I validated this is consistently working on this Rancher/UI build. I can create labels and they are desplayed in the config and YAML. I can edit them by removing and adding new ones. And I can still show them when using the hide system labels options. ✅
